"""initial delivery schema

Revision ID: 6be95a996908
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6be95a996908"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
        sa.UniqueConstraint("name", name=op.f("uq_cities_name")),
    )
    op.create_table(
        "cuisines",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuisines")),
        sa.UniqueConstraint("slug", name=op.f("uq_cuisines_slug")),
    )
    op.create_table(
        "promo_codes",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_promo_codes_positive_discount")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_codes")),
        sa.UniqueConstraint("code", name=op.f("uq_promo_codes_code")),
    )
    op.create_table(
        "users",
        sa.Column("firebase_uid", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "role",
            sa.Enum("CUSTOMER", "RESTAURANT_OWNER", "COURIER", "ADMIN", name="role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True)
    op.create_table(
        "addresses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("street", sa.String(length=200), nullable=False),
        sa.Column("house", sa.String(length=30), nullable=False),
        sa.Column("apartment", sa.String(length=30), nullable=False),
        sa.Column("entrance", sa.String(length=30), nullable=False),
        sa.Column("floor", sa.String(length=30), nullable=False),
        sa.Column("comment", sa.String(length=1000), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_addresses_city_id_cities")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_addresses_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_index(op.f("ix_addresses_user_id"), "addresses", ["user_id"], unique=False)
    op.create_table(
        "courier_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum("WALK", "BICYCLE", "SCOOTER", "CAR", name="vehicle"),
            nullable=False,
        ),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_courier_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_courier_profiles")),
    )
    op.create_table(
        "restaurants",
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("logo_url", sa.String(length=2048), nullable=False),
        sa.Column("cover_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "image_source",
            sa.Enum("RESTAURANT_UPLOAD", "GOOGLE_PLACES", "PEXELS", "SYSTEM", name="imagesource"),
            nullable=False,
        ),
        sa.Column("image_attribution", sa.String(length=1000), nullable=False),
        sa.Column("address_text", sa.String(length=400), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("minimum_order", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("base_delivery_fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estimated_delivery_min", sa.Integer(), nullable=False),
        sa.Column("estimated_delivery_max", sa.Integer(), nullable=False),
        sa.Column("opening_time", sa.Time(), nullable=False),
        sa.Column("closing_time", sa.Time(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "minimum_order >= 0 AND base_delivery_fee >= 0",
            name=op.f("ck_restaurants_positive_prices"),
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], name=op.f("fk_restaurants_city_id_cities")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_restaurants_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restaurants")),
    )
    op.create_index(op.f("ix_restaurants_city_id"), "restaurants", ["city_id"], unique=False)
    op.create_index(op.f("ix_restaurants_is_active"), "restaurants", ["is_active"], unique=False)
    op.create_index(op.f("ix_restaurants_owner_id"), "restaurants", ["owner_id"], unique=False)
    op.create_index(op.f("ix_restaurants_slug"), "restaurants", ["slug"], unique=True)
    op.create_table(
        "favorites",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_favorites_restaurant_id_restaurants"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_favorites_user_id_users")),
        sa.PrimaryKeyConstraint("user_id", "restaurant_id", name=op.f("pk_favorites")),
    )
    op.create_table(
        "menu_categories",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_menu_categories_restaurant_id_restaurants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_categories")),
        sa.UniqueConstraint("restaurant_id", "slug", name=op.f("uq_menu_categories_restaurant_id")),
    )
    op.create_index(
        op.f("ix_menu_categories_restaurant_id"), "menu_categories", ["restaurant_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=30), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_name", sa.String(length=200), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=True),
        sa.Column("delivery_address_id", sa.Uuid(), nullable=False),
        sa.Column("address_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact_phone", sa.String(length=30), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "READY_FOR_PICKUP",
                "COURIER_ASSIGNED",
                "PICKED_UP",
                "DELIVERING",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("CASH", "CARD_ON_DELIVERY", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column("payment_status", sa.String(length=30), nullable=False),
        sa.Column("customer_comment", sa.String(length=1000), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total >= 0 AND subtotal >= 0", name=op.f("ck_orders_positive_totals")),
        sa.ForeignKeyConstraint(
            ["courier_id"], ["users.id"], name=op.f("fk_orders_courier_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["users.id"], name=op.f("fk_orders_customer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"],
            ["addresses.id"],
            name=op.f("fk_orders_delivery_address_id_addresses"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], name=op.f("fk_orders_restaurant_id_restaurants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("customer_id", "idempotency_key", name=op.f("uq_orders_customer_id")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
    )
    op.create_index(op.f("ix_orders_courier_id"), "orders", ["courier_id"], unique=False)
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_customer_id"), "orders", ["customer_id"], unique=False)
    op.create_index(op.f("ix_orders_restaurant_id"), "orders", ["restaurant_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "restaurant_cuisines",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("cuisine_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cuisine_id"], ["cuisines.id"], name=op.f("fk_restaurant_cuisines_cuisine_id_cuisines")
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_restaurant_cuisines_restaurant_id_restaurants"),
        ),
        sa.PrimaryKeyConstraint("restaurant_id", "cuisine_id", name=op.f("pk_restaurant_cuisines")),
    )
    op.create_table(
        "restaurant_members",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_restaurant_members_restaurant_id_restaurants"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_restaurant_members_user_id_users")
        ),
        sa.PrimaryKeyConstraint("restaurant_id", "user_id", name=op.f("pk_restaurant_members")),
    )
    op.create_table(
        "courier_deliveries",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("courier_id", sa.Uuid(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"], ["users.id"], name=op.f("fk_courier_deliveries_courier_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_courier_deliveries_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courier_deliveries")),
        sa.UniqueConstraint("order_id", name=op.f("uq_courier_deliveries_order_id")),
    )
    op.create_index(
        op.f("ix_courier_deliveries_courier_id"), "courier_deliveries", ["courier_id"], unique=False
    )
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "READY_FOR_PICKUP",
                "COURIER_ASSIGNED",
                "PICKED_UP",
                "DELIVERING",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "READY_FOR_PICKUP",
                "COURIER_ASSIGNED",
                "PICKED_UP",
                "DELIVERING",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
            name=op.f("fk_order_status_history_changed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_status_history_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        op.f("ix_order_status_history_order_id"), "order_status_history", ["order_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("menu_category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("weight_value", sa.Integer(), nullable=True),
        sa.Column("weight_unit", sa.String(length=20), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "image_source",
            sa.Enum("RESTAURANT_UPLOAD", "GOOGLE_PLACES", "PEXELS", "SYSTEM", name="imagesource"),
            nullable=False,
        ),
        sa.Column("image_attribution", sa.String(length=1000), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price >= 0", name=op.f("ck_products_positive_price")),
        sa.ForeignKeyConstraint(
            ["menu_category_id"],
            ["menu_categories.id"],
            name=op.f("fk_products_menu_category_id_menu_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            name=op.f("fk_products_restaurant_id_restaurants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("restaurant_id", "slug", name=op.f("uq_products_restaurant_id")),
    )
    op.create_index(op.f("ix_products_is_available"), "products", ["is_available"], unique=False)
    op.create_index(
        op.f("ix_products_menu_category_id"), "products", ["menu_category_id"], unique=False
    )
    op.create_index(op.f("ix_products_restaurant_id"), "products", ["restaurant_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("author_name", sa.String(length=100), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_reviews_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"], ["restaurants.id"], name=op.f("fk_reviews_restaurant_id_restaurants")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("order_id", name=op.f("uq_reviews_order_id")),
    )
    op.create_index(op.f("ix_reviews_restaurant_id"), "reviews", ["restaurant_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("product_image_url", sa.String(length=2048), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_positive_quantity")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_items_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_reviews_restaurant_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_products_restaurant_id"), table_name="products")
    op.drop_index(op.f("ix_products_menu_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_is_available"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_order_status_history_order_id"), table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_courier_deliveries_courier_id"), table_name="courier_deliveries")
    op.drop_table("courier_deliveries")
    op.drop_table("restaurant_members")
    op.drop_table("restaurant_cuisines")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_restaurant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_customer_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_courier_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_menu_categories_restaurant_id"), table_name="menu_categories")
    op.drop_table("menu_categories")
    op.drop_table("favorites")
    op.drop_index(op.f("ix_restaurants_slug"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_owner_id"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_is_active"), table_name="restaurants")
    op.drop_index(op.f("ix_restaurants_city_id"), table_name="restaurants")
    op.drop_table("restaurants")
    op.drop_table("courier_profiles")
    op.drop_index(op.f("ix_addresses_user_id"), table_name="addresses")
    op.drop_table("addresses")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_table("users")
    op.drop_table("promo_codes")
    op.drop_table("cuisines")
    op.drop_table("cities")
    # ### end Alembic commands ###
